#!/usr/bin/env python3
"""
Generate the FLASH Config file dynamically based on the LAYERS list
defined in flashPar.py.

Usage:
    python generateConfig.py            # writes Config in current directory
    python generateConfig.py /path/to/  # writes Config at specified path

Run this BEFORE calling the FLASH setup script.
"""

import os
import sys

# Import LAYERS and CHAMBER from flashPar
base_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, base_dir)
from flashPar import CHAMBER, CUSTOM_DENS_MAP, LAYERS

print(f"[generateConfig] Generating Config using {base_dir}/flashPar.py")


def main():
    outpath = None
    if len(sys.argv) > 1:
        outpath = sys.argv[1]
        if os.path.isdir(outpath):
            outpath = os.path.join(outpath, "Config")
    generate_config(outpath)


def generate_config(output_path=None):
    if output_path is None:
        output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Config")

    lines = []

    # ---- Header ----
    lines.append("# Configuration file for LaserSlab simulation")
    lines.append("# AUTO-GENERATED by generateConfig.py - do not edit manually")
    lines.append(f"# Layers: {', '.join(l['name'] for l in LAYERS)}")
    lines.append("")
    lines.append("REQUIRES Driver")
    lines.append("REQUIRES physics/Hydro")
    lines.append("")
    lines.append("USESETUPVARS ThreeT")
    lines.append("")
    lines.append("IF ThreeT")
    lines.append("   REQUESTS physics/Diffuse/DiffuseMain/Unsplit")
    lines.append("")
    lines.append(
        "   REQUESTS physics/sourceTerms/Heatexchange/HeatexchangeMain/Spitzer"
    )
    lines.append(
        "   REQUESTS physics/materialProperties/Conductivity/ConductivityMain/SpitzerHighZ"
    )
    lines.append("ENDIF")
    lines.append("")

    # ---- Species setup note ----
    species_str = ",".join(["cham"] + [l["name"] for l in LAYERS])
    lines.append("# This simulation requires specifying the species via the setup")
    lines.append("# line. You must include the species setup variable:")
    lines.append("#")
    lines.append(f"# species={species_str}")
    lines.append("#")
    lines.append("")

    # ---- Data files ----
    # Collect unique data files from all layers and chamber
    datafiles = set()
    datafiles.add(CHAMBER["eosFile"])
    datafiles.add(CHAMBER["opFileName"])
    for layer in LAYERS:
        datafiles.add(layer["eosFile"])
        datafiles.add(layer["opFileName"])

    for df in sorted(datafiles):
        lines.append(f"DATAFILES {df}")
    lines.append("")

    # ---- Runtime Parameters ----
    lines.append("##########################")
    lines.append("#                        #")
    lines.append("#   RUNTIME PARAMETERS   #")
    lines.append("#                        #")
    lines.append("##########################")
    lines.append("")

    # Radiation source parameters (unchanged)
    lines.append("## Radiation source runtime parameters:")
    lines.append("D sim_radSlab Switch to enable radiation temperature BC")
    lines.append("PARAMETER sim_radSlab BOOLEAN False")
    lines.append("")
    lines.append(
        "D sim_radSourceType radiation source temperature type (0=constant, 1=Gaussian)"
    )
    lines.append("PARAMETER sim_radSourceType  INTEGER 0")
    lines.append("")
    lines.append(
        "D sim_radSourceTMax peak radiation temperature (eV) of the radiation source at domain boundary"
    )
    lines.append("PARAMETER sim_radSourceTMax  REAL 500.")
    lines.append("")
    lines.append(
        "D sim_radSourceTMin minimum radiation temperature (eV) of the radiation source at domain boundary"
    )
    lines.append("PARAMETER sim_radSourceTMin  REAL 500.")
    lines.append("")
    lines.append("D sim_radSourceStart start time for radiation source")
    lines.append("PARAMETER sim_radSourceStart  REAL 0.")
    lines.append("")
    lines.append("D sim_radSourceStop stop time for radiation source")
    lines.append("PARAMETER sim_radSourceStop  REAL 1.e99")
    lines.append("")
    lines.append("D sim_radSourcePeak time at which radiation source Gaussian peaks")
    lines.append("PARAMETER sim_radSourcePeak  REAL 1.e-9")
    lines.append("")
    lines.append("D sim_radSourceFWHM fwhm of radiation source Gaussian")
    lines.append("PARAMETER sim_radSourceFWHM  REAL 1.e-9")
    lines.append("")

    # Geometry parameters
    lines.append("D sim_initGeom Use a spherical target if sphere, default to slab")
    lines.append('PARAMETER sim_initGeom STRING "slab" ["slab","sphere"]')
    lines.append("")
    lines.append(
        "D sim_vacuumHeight The thickness of the vacuum region in front of the target"
    )
    lines.append("PARAMETER sim_vacuumHeight REAL 0.0200")
    lines.append("")

    # Number of layers
    lines.append("D sim_numLayers Number of target layers")
    lines.append(f"PARAMETER sim_numLayers INTEGER {len(LAYERS)}")
    lines.append("")

    # Per-layer parameters
    for idx, layer in enumerate(LAYERS):
        n = idx + 1
        name = layer["name"]
        lines.append(f"# --- Layer {n}: {name} ---")
        lines.append(f"D sim_rho_{n} Initial density for layer {n} ({name})")
        lines.append(f"PARAMETER sim_rho_{n}   REAL {layer['rho']}")
        lines.append("")
        lines.append(
            f"D sim_tele_{n} Initial electron temperature for layer {n} ({name})"
        )
        lines.append(f"PARAMETER sim_tele_{n}  REAL {layer['tele']}")
        lines.append("")
        lines.append(f"D sim_tion_{n} Initial ion temperature for layer {n} ({name})")
        lines.append(f"PARAMETER sim_tion_{n}  REAL {layer['tion']}")
        lines.append("")
        lines.append(
            f"D sim_trad_{n} Initial radiation temperature for layer {n} ({name})"
        )
        lines.append(f"PARAMETER sim_trad_{n}  REAL {layer['trad']}")
        lines.append("")
        lines.append(f"D sim_height_{n} Thickness of layer {n} ({name}) in y-direction")
        lines.append(f"PARAMETER sim_height_{n} REAL {layer['height']}")
        lines.append("")
        lines.append(f"D sim_radius_{n} Radial extent of layer {n} ({name})")
        lines.append(f"PARAMETER sim_radius_{n} REAL {layer['radius']}")
        lines.append("")

    # Chamber parameters
    lines.append("# --- Chamber (background) ---")
    lines.append("D sim_rhoCham Initial chamber density")
    lines.append(f"PARAMETER sim_rhoCham   REAL {CHAMBER['rho']}")
    lines.append("")
    lines.append("D sim_teleCham Initial chamber electron temperature")
    lines.append(f"PARAMETER sim_teleCham  REAL {CHAMBER['tele']}")
    lines.append("")
    lines.append("D sim_tionCham Initial chamber ion temperature")
    lines.append(f"PARAMETER sim_tionCham  REAL {CHAMBER['tion']}")
    lines.append("")
    lines.append("D sim_tradCham Initial chamber radiation temperature")
    lines.append(f"PARAMETER sim_tradCham  REAL {CHAMBER['trad']}")
    lines.append("")

    # Custom density map parameters
    lines.append("# --- Custom density map ---")
    lines.append(
        "D sim_customDensMap If true, load density/species from external .npz file"
    )
    lines.append("PARAMETER sim_customDensMap BOOLEAN False")
    lines.append("")
    lines.append("D sim_densMapFile Path to the .npz density map file")
    lines.append('PARAMETER sim_densMapFile STRING "density_map.npz"')
    lines.append("")

    # Variable declaration
    lines.append(
        "D lase_variable saves (density of) the irradiated energy from EnergyDeposition unit"
    )
    lines.append("VARIABLE lase TYPE: PER_VOLUME")
    lines.append("")

    # Thomson Scattering demo (unchanged)
    lines.append("USESETUPVARS ThscDemo")
    lines.append("IF ThscDemo")
    lines.append("")
    lines.append("   REQUIRES diagnostics/ThomsonScattering")
    lines.append("")
    lines.append(
        "   D pwin_variable for debugging: density of Power In from Thomson probe laser"
    )
    lines.append(
        "   D pwia_variable for debugging: density of Power In, except where forbidden by critical density"
    )
    lines.append(
        "   D pwi1_variable for debugging: density of Power In, attenuated by close-to-critical energy loss"
    )
    lines.append(
        "   D pwi2_variable for debugging: density of Power In, attenuated by close-to-critical energy loss along both legs"
    )
    lines.append(
        "   D pwde_variable for debugging: density of Power of light from Thomson scattering region detected"
    )
    lines.append(
        "   D pwd1_variable for debugging: density of Power of light, attenuated"
    )
    lines.append(
        "   D pwd2_variable for debugging: density of Power of light, (2 legs) attenuated"
    )
    lines.append("")
    lines.append("   VARIABLE pwin")
    lines.append("   VARIABLE pwia")
    lines.append(
        "#   VARIABLE pwi1    # Uncommenting this makes ThomsonScattering MUCH slower!"
    )
    lines.append("   VARIABLE pwde")
    lines.append("#   VARIABLE pwda")
    lines.append("   VARIABLE pwd1")
    lines.append("   VARIABLE pwi2")
    lines.append("   VARIABLE pwd2")
    lines.append("")
    lines.append("ENDIF")
    lines.append("")

    # Write
    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(
        f"[generateConfig] Wrote Config with {len(LAYERS)} layer(s) to: {output_path}"
    )
    print(f"[generateConfig] Species string: species={species_str}")


if __name__ == "__main__":
    main()
